name: Build and Push Docker Image

# Triggers the workflow on pushes and when a tag is created
on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx (for building multi-architecture images, if needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to DockerHub using secrets
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Extract the tag name or default to "latest" if not on a tagged commit
      - name: Extract Docker Tag
        id: docker_tag
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "tag=latest" >> $GITHUB_ENV
          else
            TAG_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
            echo "tag=${TAG_NAME}" >> $GITHUB_ENV
          fi

      # Build and push the Docker image to DockerHub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: cvcore/pdfnamer:${{ env.tag }}
